[package]
name = "rustyfish"
version = "0.11.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustyfish"
crate-type = ["cdylib"]

[dependencies]
jellyfish = "0.3.0"
pyo3 = "0.18.1"
